name: go-macos

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        go-version: ["1.25.x"]

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v5
      - uses: cloudengio/.github/.github/actions/go@main
      - uses: cloudengio/.github/.github/actions/apple-keychain@macos-signing
        id: create-keychain
        with:
          certificate-p12-base64: ${{ secrets.APPLE_SIGNING_CERTIFICATE }}
      - uses: cloudengio/.github/.github/actions/apple-provisioning@macos-signing
        with:
          provisioning-profile-base64: ${{ secrets.APPLE_PROVISIONING_PROFILE }}
          provisioning-profile-location: "provisioning.profile"
      - name: install keychain plugin
        env:
          CLOUDENG_SIGNING: ${{ secrets.CLOUDENG_SIGNING }}
          CLOUDENG_KEYCHAIN_PROFILE: $RUNNER_TEMP/provisioning.profile
          CLOUDENG_DEVID: ${{ secrets.CLOUDENG_DEVID }}
          CLOUDENG_KEYCHAIN_IDENTIFIER: "keychain-github"
          GOBUNDLE_VERBOSE: "yes"

        run: |
          # security list-keychain -d user
          # security dump-keychain $(security list-keychain -d user)

          go install cloudeng.io/macos/cmd/gobundle@latest
          (cd cmd/keychain-plugin; go generate .)
          macos-keychain-plugin --help || true

          codesign -dv --verbose=4 /Users/runner/go/bin/macos-keychain-plugin
          codesign -dv --entitlements - --xml /Users/runner/go/bin/macos-keychain-plugin 2>&1 | grep xml | tidy -xml -i -q
          security cms -D -i /Users/runner/work/_temp/provisioning.profile

      - name: test
        run: |
          set -x

          KEYCHAIN_PATH=${{ steps.create-keychain.outputs.keychain-path }}
          security default-keychain -s $KEYCHAIN_PATH
          echo $KEYCHAIN_PATH
          echo "default keychain: $(security default-keychain)"
          echo "all keychains: $(security list-keychains)"
          echo "user keychains: $(security list-keychains -d user)"

          security add-generic-password -a "$USER" -s "service_name_0" -w "password_value_0" $KEYCHAIN_PATH
          security add-generic-password -a "$USER" -s "service_name_1" -w "password_value_1"

          echo "with path"
          security dump-keychain $KEYCHAIN_PATH | grep service_name
          echo "without path"
          security dump-keychain | grep service_name

          multimod --config=.multimod.yaml test || true

          log show --debug -last 1m | grep keychain

          exit 1

      - name: cleanup
        if: always()
        run: |
          KEYCHAIN_PATH=${{ steps.create-keychain.outputs.keychain-path }}
          echo "Deleting keychain at $KEYCHAIN_PATH"
          security delete-keychain "$KEYCHAIN_PATH" || true
  lint:
    uses: cloudengio/.github/.github/workflows/go-lint-multimod.yml@main
    with:
      os-version: macos-latest
      go-version: "1.25.x"
