name: go-macos

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        go-version: ["1.25.x"]

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v5
      - uses: cloudengio/.github/.github/actions/go@main
      - uses: cloudengio/.github/.github/actions/apple-signing-provisioning@macos-signing
        with:
          provisioning-profile-base64: ${{ secrets.APPLE_PROVISIONING_PROFILE }}
          provisioning-profile-location: "provisioning.profile"
          certificate-p12-base64: ${{ secrets.APPLE_SIGNING_CERTIFICATE }}
      - name: install keychain plugin
        env:
          CLOUDENG_SIGNING: ${{ secrets.CLOUDENG_SIGNING }}
          CLOUDENG_KEYCHAIN_PROFILE: $RUNNER_TEMP/provisioning.profile
          CLOUDENG_DEVID: ${{ secrets.CLOUDENG_DEVID }}
          CLOUDENG_KEYCHAIN_IDENTIFIER: "keychain-github"
          GOBUNDLE_VERBOSE: "yes"
        run: |
          # security list-keychain -d user
          # security dump-keychain $(security list-keychain -d user)

          go install cloudeng.io/macos/cmd/gobundle@latest
          (cd cmd/keychain-plugin; go generate .)

          # codesign -dv --verbose=4 /Users/runner/go/bin/macos-keychain-plugin
          # codesign -dv --entitlements - --xml /Users/runner/go/bin/macos-keychain-plugin 2>&1 | grep xml | tidy -xml -i -q
          # security cms -D -i /Users/runner/work/_temp/provisioning.profile

      - name: test
        run: |
          security list-keychains
          security list-keychains -d user
          security dump-keychain $(security list-keychains -d user)
          multimod --config=.multimod.yaml test

  lint:
    uses: cloudengio/.github/.github/workflows/go-lint-multimod.yml@main
    with:
      os-version: macos-latest
      go-version: "1.25.x"
